function H_ss = tf_from_sym(H_sym)
    s = sym('s');
    [num_sym, den_sym] = numden(H_sym);
    num_coeffs = coeffs(num_sym, s, 'All');
    den_coeffs = coeffs(den_sym, s, 'All');
    [A, B, C, D] = tf2ss(num_coeffs, den_coeffs);
    H_ss = struct( ...
        'A', A, ...
        'B', B, ...
        'C', C,...
        'D', D...
    );
end
