function [vds, vgs, id, capacitances, capacitance_vds, G1, G2, H1, H2, H3] = simulink_variables(Z_i_s, Z_o_p, Z_o_s, r_g, c_g, vds_divisor, vgs_divisor, max_vds)
[~, ~, ~, ~, vds, vgs, id, capacitance_vds, capacitances, Y_iss_g, Y_oss_g, Y_rss_g, Y_iss_d, Y_oss_d, Y_rss_d, G_g, G_d, G_s] = fet_large_signal(Z_i_s, Z_o_p, Z_o_s, r_g, c_g, vds_divisor, vgs_divisor, max_vds);
[~, ~, ~, ~, ~, G1, G2, ~, ~, H1, H2, H3, ~, ~, ~] = control_loop(60, 10, Z_o_p, Z_o_s, r_g, c_g, 1, 1, max_vds);

[Y_iss_g_num, Y_iss_g_den] = numden_coeffs(Y_iss_g);
createTFSubsystem(Y_iss_g_num, Y_iss_g_den, 'LoopSimulation', 'FET/Y_iss_g_test', 'v_i', 'v_gs_iss');
[Y_oss_g_num, Y_oss_g_den] = numden_coeffs(Y_oss_g);
[Y_rss_g_num, Y_rss_g_den] = numden_coeffs(Y_rss_g);
[Y_iss_d_num, Y_iss_d_den] = numden_coeffs(Y_iss_d);
[Y_oss_d_num, Y_oss_d_den] = numden_coeffs(Y_oss_d);
[Y_rss_d_num, Y_rss_d_den] = numden_coeffs(Y_rss_d);
[G_g_num, G_g_den] = numden_coeffs(G_g);
[G_d_num, G_d_den] = numden_coeffs(G_d);
[G_s_num, G_s_den] = numden_coeffs(G_s);

matlabFunctionBlock('LoopSimulation/FET/gains', ...
    Y_iss_g_num, ...
    Y_iss_g_den, ...
    Y_oss_g_num, ...
    Y_oss_g_den, ...
    Y_rss_g_num, ...
    Y_rss_g_den, ...
    Y_iss_d_num, ...
    Y_iss_d_den, ...
    Y_oss_d_num, ...
    Y_oss_d_den, ...
    Y_rss_d_num, ...
    Y_rss_d_den, ...
    G_g_num, ...
    G_g_den, ...
    G_d_num, ...
    G_d_den, ...
    G_s_num, ...
    G_s_den, ...
"Vars",[sym('C_iss'), sym('C_oss'), sym('C_rss')]);

capacitances = [capacitances.C_iss	capacitances.C_oss	capacitances.C_rss];

coeffs_func = @calculate_coeffs;
end